# Generated by Django 3.1.6 on 2021-03-08 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=11)),
                ('estado_civil', models.CharField(blank=True, choices=[('C', 'Casado(a)'), ('S', 'Solteiro(a)'), ('V', 'Viúvo(a)')], max_length=50, verbose_name='Estado Civil')),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=50, verbose_name='Sexo')),
                ('formacao', models.CharField(blank=True, choices=[('CursandoTecn', 'Cursando Técnico'), ('CompletoTecn', 'Técnico Completo'), ('CursandoTecnologia', 'Cursando Tecnologia'), ('CompletoTecnologia', 'Tecnologia Completo'), ('CursandoLicen', 'Cursando Licenciatura'), ('CompletoLicen', 'Licenciatura Completo'), ('CursandoBacha', 'Cursando Bacharelado'), ('CompletoBacha', 'Bacharelado Completo'), ('CursandoMest', 'Cursando Mestrado'), ('CompletoMest', 'Mestrado Completo')], max_length=50, verbose_name='Formação')),
                ('curso', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
