# Generated by Django 3.1.6 on 2021-03-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Casado(a)', 'Casado(a)'), ('Solteiro(a)', 'Solteiro(a)'), ('Viúvo(a)', 'Viúvo(a)')], max_length=50, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='formacao',
            field=models.CharField(blank=True, choices=[('Cursando Técnico', 'Cursando Técnico'), ('Técnico Completo', 'Técnico Completo'), ('Cursando Tecnologia', 'Cursando Tecnologia'), ('Tecnologia Completo', 'Tecnologia Completo'), ('Cursando Licenciatura', 'Cursando Licenciatura'), ('Licenciatura Completo', 'Licenciatura Completo'), ('Cursando Bacharelado', 'Cursando Bacharelado'), ('Bacharelado Completo', 'Bacharelado Completo'), ('Cursando Mestrado', 'Cursando Mestrado'), ('Mestrado Completo', 'Mestrado Completo')], max_length=50, verbose_name='Formação'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], max_length=50, verbose_name='Sexo'),
        ),
    ]
