# Generated by Django 3.1.6 on 2021-03-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210308_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Casado', 'Casado'), ('Solteiro', 'Solteiro'), ('Viúvo', 'Viúvo')], max_length=50, verbose_name='Estado Civil'),
        ),
    ]
